// <auto-generated />
using System;
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20220409173618_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "camisetas",
                            CreatedAt = new DateTime(2022, 4, 9, 14, 36, 18, 388, DateTimeKind.Local).AddTicks(6244),
                            Description = "Foram essas as palavras que tornaram o mago cinza imortalizado, pegando toda a experiência da vitória para si, subindo de classe e virando o poderoso mago branco. Enfrentar um chefe de alto nível sozinho pode te render um desafio mortal, mas a vitória te faz ficar alguns níveis a frente de seu grupo.",
                            ImageUrl = "https://cdn.nerdstore.com.br/wp-content/uploads/2021/03/camiseta-you-shall-not-pass-01.jpg",
                            Name = "Camiseta You Shall Not Pass",
                            Price = 50m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "camisetas",
                            CreatedAt = new DateTime(2022, 4, 9, 14, 36, 18, 388, DateTimeKind.Local).AddTicks(6263),
                            Description = "A Árvore de Gondor representa a paz e prosperidade dos Homens, as estrelas se referem aos sete barcos dos Homens de Númenor que traziam as Palantír, cada um com o desenho de uma estrela.Sua estampa favorita,  agora na sua versão black edition, em uma super camiseta pronta para desbravar a Terra Média!",
                            ImageUrl = "https://cdn.nerdstore.com.br/wp-content/uploads/2022/04/vitrine-camiseta-arvore-de-gondor-black-edition-01-nerdstore.jpg",
                            Name = "Camiseta Árvore de Gondor – Black Edition",
                            Price = 79.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
